name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '17' ]
        os: [ubuntu-latest, windows-latest]
    name: Java ${{ matrix.Java }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
      - run: echo "test Java ${{ matrix.Java }} on ${{ matrix.os }}" > ~/.m2/"Java ${{ matrix.Java }} on ${{ matrix.os }}"

    foo:
      runs-on: ubuntu-latest
      needs: build
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
      - run: ls -l ~/.m2